diag_elements_gamma: [500, 500, 25, 25, 25]
diag_elements_lambda: [10, 10, 10, 10, 10]
diag_elements_b: [50, 50]

velocity_virtual_threshold: 10.0
los_distance_threshold: 4.0
speed_min: 0.0
speed_max: 1.0
steer_min: -0.52
steer_max: 0.52
k_p_speed: 1.0
k_i_speed: 0.05
k_p_steer: 0.5
vehicle_length: 0.4
